config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/authorize' => 'auth#gettoken'
  get '/feedbacks', to: 'feedbacks#new'
  post '/feedbacks', to: 'feedbacks#create'
  resources :feedbacks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
    include AuthHelper

    # 認可コードからアクセストークンを取得
    def gettoken
      token = get_token_from_code params[:code]
      session[:kintone_token] = token.to_hash
      redirect_to feedbacks_url
    end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
    include AuthHelper
   
    # kintoenのアプリケーションID
    APP_ID = '117'
  
    def new
      # 初期ページロード状態では何もしない
    end
    
    def create
      @feedback = Feedback.new(feedback_params)
      if @feedback.save
        token = get_access_token
  
        if token
          # アクセストークンがすでに取得されている場合、データをkintoneへポスト
          
          # ハッシュ形式でレコードを設定
          # 
          record = {
            "app" => APP_ID,
            "record" => {
              "Received_via" => {
                "value" => feedback_params[:received_via]
              },
              "Category" => {
                "value" => feedback_params[:category]
              },
              "Tenant_name" => {
                "value" => feedback_params[:tenant_name]
              },
              "Opinion" => {
                "value" => feedback_params[:opinion]
              }
            }
          }
          
          response = token.post('https://devxorudc.cybozu.com/k/v1/record.json', {:body => record.to_json, :headers => {'Authorization' => 'Bearer #{token.token}', 'Content-Type' => 'application/json'}})
          
          redirect_to feedbacks_url
        else
          # アクセストークンが存在しない場合、ホームページへ戻り、承認のやり直し
          # 
          redirect_to root_url
        end
      else
        render 'new'
      end
    end
      
    private
      def feedback_params
        # フォームからデータを取得
        params.require(:feedback).permit(:received_via, :category, :tenant_name, :opinion)
      end
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
    include AuthHelper

    def index
      # 承認リンクの表示
      @login_url = get_login_url
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper

    # kintone側のOAuth設定のクライアントID
    CLIENT_ID = 'l.1.6yj9tvyxuue0iclewfa3gp3thug4zjrm'
    # kintone側のOAuth設定のクライアントシークレット
    CLIENT_SECRET = 'em9pph5rzj91duv42v0ry4kkkcothzm4vjd487ykfkxwlaafuwl3e5eiodwsq2dk'
    # kintoneのURL
    SITE = 'https://devxorudc.cybozu.com'
    # 認可エンドポイント
    AUTHORIZE_URL = '/oauth2/authorization'
    # トークンエンドポイント
    TOKEN_URL = '/oauth2/token'
  
    # APIアクセスのスコープ設定 read/write権限
    SCOPES = [ 'k:app_record:read','k:app_record:write' ]
  
    # CSRF対策のランダムな値
    STATE = SecureRandom.alphanumeric
  
    # ログインURLの生成
    def get_login_url
      client = OAuth2::Client.new(CLIENT_ID,
                                  CLIENT_SECRET,
                                  :site => SITE,
                                  :authorize_url => AUTHORIZE_URL,
                                  :token_url => TOKEN_URL)
  
      login_url = client.auth_code.authorize_url( :redirect_uri => authorize_url, # Railsの認可ページへのルートパス
                                                  :scope => SCOPES.join(' '), 
                                                  :state => STATE)
    end
  
    # アクセストークン取得のための認可コードを送信
    def get_token_from_code(auth_code)
      client = OAuth2::Client.new(CLIENT_ID,
                                  CLIENT_SECRET,
                                  :site => SITE,
                                  :authorize_url => AUTHORIZE_URL,
                                  :token_url => TOKEN_URL)
                                  
      token = client.auth_code.get_token(auth_code,
                                          :redirect_uri => authorize_url,
                                          :scope => SCOPES.join(' '))
    end
  
    # アクセストークンの取得
    def get_access_token
      # セッションから現在のアクセストークンハッシュを取得
      token_hash = session[:kintone_token]
  
      client = OAuth2::Client.new(CLIENT_ID,
                                  CLIENT_SECRET,
                                  :site => SITE,
                                  :authorize_url => AUTHORIZE_URL,
                                  :token_url => TOKEN_URL)
  
      token = OAuth2::AccessToken.from_hash(client, token_hash)
  
      # アクセストークンが期限切れの場合、リフレッシュトークンからアクセストークンを取得
      if token.expired?
        new_token = token.refresh!
        # 新アクセストークンをセッションへ保存
        session[:kintone_token] = new_token.to_hash
        access_token = new_token
      else
        access_token = token
      end
    end
  end
  

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/feedbacks/new.html.erb
<h1>お客様の声</h1>
<%= form_for :feedback, url: feedbacks_path do |form| %>
  <p>
    <%= form.hidden_field :received_via, value: "WEBサイトから" %>
    <%= form.label :category, "カテゴリ:" %><br>
    <%= form.select :category,
      [['---','---'],
        ['お褒め','お褒め'],
        ['お叱り','お叱り'],
        ['ご要望','ご要望'],
        ['その他','その他'],] 
    %>
  </p>
  <p>
    <%= form.label :tenant_name, "テナント名:" %><br>
    <%= form.select :tenant_name,
      [['---',''],
        ['坊主食品','坊主食品'],
        ['サイボシューズ','サイボシューズ'],
        ['Ｃミュージックストア','Ｃミュージックストア'],
        ['施設','施設'],]
    %>
  </p>
  <p>
    <%= form.label :opinion, "ご意見内容:" %><br>
    <%= form.text_area :opinion, size: "50x6" %>
  </p>

  <p>
    <%= form.submit "送信" %>
  </p>
<% end %>

app/views/home/index.html.erb
<h1>kintone OAuth 2.0 クライアントサンプル</h1>
  <p>
    <a href="<%= @login_url %>" role="button" id="connect-button">kintoneに接続</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomerFeedback</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>